import 'package:flutter/material.dart';
import 'package:flutterapp/haiapp/generatediphone11promax13widget/generated/GeneratedBluetoothWidget.dart';
import 'package:flutterapp/haiapp/generatediphone11promax13widget/generated/GeneratedCall_endWidget.dart';
import 'package:flutterapp/haiapp/generatediphone11promax13widget/generated/GeneratedHoldWidget.dart';
import 'package:flutterapp/haiapp/generatediphone11promax13widget/generated/GeneratedPhone_bluetooth_speakerWidget.dart';
import 'package:flutterapp/haiapp/generatediphone11promax13widget/generated/GeneratedAddWidget.dart';
import 'package:flutterapp/haiapp/generatediphone11promax13widget/generated/GeneratedUBClinicWidget.dart';
import 'package:flutterapp/haiapp/generatediphone11promax13widget/generated/GeneratedMuteWidget.dart';
import 'package:flutterapp/haiapp/generatediphone11promax13widget/generated/GeneratedRectangle8Widget5.dart';
import 'package:flutterapp/haiapp/generatediphone11promax13widget/generated/GeneratedRectangle9Widget.dart';
import 'package:flutterapp/haiapp/generatediphone11promax13widget/generated/GeneratedSpeakerWidget.dart';
import 'package:flutterapp/haiapp/generatediphone11promax13widget/generated/GeneratedCallWidget1.dart';
import 'package:flutterapp/haiapp/generatediphone11promax13widget/generated/GeneratedOutgoingWidget.dart';
import 'package:flutterapp/haiapp/generatediphone11promax13widget/generated/GeneratedMic_offWidget.dart';
import 'package:flutterapp/haiapp/generatediphone11promax13widget/generated/GeneratedAddcallWidget.dart';
import 'package:flutterapp/haiapp/generatediphone11promax13widget/generated/GeneratedDialpadWidget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/haiapp/generatediphone11promax13widget/generated/GeneratedPauseWidget.dart';
import 'package:flutterapp/haiapp/generatediphone11promax13widget/generated/GeneratedKeypadWidget.dart';
import 'package:flutterapp/haiapp/generatediphone11promax13widget/generated/GeneratedHotlineWidget.dart';
import 'package:flutterapp/haiapp/generatediphone11promax13widget/generated/GeneratedVolume_upWidget.dart';
import 'package:flutterapp/haiapp/generatediphone11promax13widget/generated/GeneratedEndCallWidget.dart';

/* Frame iPhone 11 Pro Max - 13
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProMax13Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Visibility(
      visible: false,
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Container(
          width: 414.0,
          height: 896.0,
          child: Stack(
              fit: StackFit.expand,
              alignment: Alignment.center,
              overflow: Overflow.visible,
              children: [
                ClipRRect(
                  borderRadius: BorderRadius.zero,
                  child: Container(
                    color: Color.fromARGB(255, 183, 169, 201),
                  ),
                ),
                Positioned(
                  left: 0.000244140625,
                  top: 148.0,
                  right: null,
                  bottom: null,
                  width: 414.0007629394531,
                  height: 747.7596435546875,
                  child: GeneratedRectangle8Widget5(),
                ),
                Positioned(
                  left: 30.0,
                  top: 449.0,
                  right: null,
                  bottom: null,
                  width: 96.0,
                  height: 96.0,
                  child: GeneratedAddWidget(),
                ),
                Positioned(
                  left: 289.0,
                  top: 449.0,
                  right: null,
                  bottom: null,
                  width: 96.0,
                  height: 96.0,
                  child: GeneratedPhone_bluetooth_speakerWidget(),
                ),
                Positioned(
                  left: 30.0,
                  top: 605.0,
                  right: null,
                  bottom: null,
                  width: 96.0,
                  height: 96.0,
                  child: GeneratedVolume_upWidget(),
                ),
                Positioned(
                  left: 160.0,
                  top: 605.0,
                  right: null,
                  bottom: null,
                  width: 96.0,
                  height: 96.0,
                  child: GeneratedMic_offWidget(),
                ),
                Positioned(
                  left: 160.0,
                  top: 449.0,
                  right: null,
                  bottom: null,
                  width: 96.0,
                  height: 96.0,
                  child: GeneratedPauseWidget(),
                ),
                Positioned(
                  left: 0.0,
                  top: 0.0,
                  right: 0.0,
                  bottom: 0.0,
                  width: null,
                  height: null,
                  child: LayoutBuilder(builder:
                      (BuildContext context, BoxConstraints constraints) {
                    final double width =
                        constraints.maxWidth * 0.10386473429951691;

                    final double height =
                        constraints.maxHeight * 0.03459821428571429;

                    return Stack(children: [
                      TransformHelper.translate(
                          x: constraints.maxWidth * 0.47342995169082125,
                          y: constraints.maxHeight * 0.6116071428571429,
                          z: 0,
                          child: Container(
                            width: width,
                            height: height,
                            child: GeneratedHoldWidget(),
                          ))
                    ]);
                  }),
                ),
                Positioned(
                  left: 289.0,
                  top: 605.0,
                  right: null,
                  bottom: null,
                  width: 96.0,
                  height: 96.0,
                  child: GeneratedDialpadWidget(),
                ),
                Positioned(
                  left: 160.0,
                  top: 746.0,
                  right: null,
                  bottom: null,
                  width: 96.0,
                  height: 68.0,
                  child: GeneratedCall_endWidget(),
                ),
                Positioned(
                  left: 47.0,
                  top: 548.0,
                  right: null,
                  bottom: null,
                  width: 70.0,
                  height: 20.0,
                  child: GeneratedAddcallWidget(),
                ),
                Positioned(
                  left: 301.0,
                  top: 546.0,
                  right: null,
                  bottom: null,
                  width: 77.0,
                  height: 23.0,
                  child: GeneratedBluetoothWidget(),
                ),
                Positioned(
                  left: 52.0,
                  top: 701.0,
                  right: null,
                  bottom: null,
                  width: 64.0,
                  height: 33.0,
                  child: GeneratedSpeakerWidget(),
                ),
                Positioned(
                  left: 189.0,
                  top: 705.0,
                  right: null,
                  bottom: null,
                  width: 43.0,
                  height: 24.0,
                  child: GeneratedMuteWidget(),
                ),
                Positioned(
                  left: 317.0,
                  top: 705.0,
                  right: null,
                  bottom: null,
                  width: 57.0,
                  height: 24.0,
                  child: GeneratedKeypadWidget(),
                ),
                Positioned(
                  left: 179.0,
                  top: 814.0,
                  right: null,
                  bottom: null,
                  width: 61.0,
                  height: 21.0,
                  child: GeneratedEndCallWidget(),
                ),
                Positioned(
                  left: 115.0,
                  top: 100.0,
                  right: null,
                  bottom: null,
                  width: 177.0,
                  height: 49.0,
                  child: GeneratedUBClinicWidget(),
                ),
                Positioned(
                  left: 136.0,
                  top: 63.0,
                  right: null,
                  bottom: null,
                  width: 24.0,
                  height: 24.0,
                  child: GeneratedCallWidget1(),
                ),
                Positioned(
                  left: 168.0,
                  top: 66.0,
                  right: null,
                  bottom: null,
                  width: 69.0,
                  height: 24.0,
                  child: GeneratedOutgoingWidget(),
                ),
                Positioned(
                  left: 289.0,
                  top: 118.0,
                  right: null,
                  bottom: null,
                  width: 56.0,
                  height: 21.0,
                  child: GeneratedHotlineWidget(),
                ),
                Positioned(
                  left: 50.0,
                  top: 160.0,
                  right: null,
                  bottom: null,
                  width: 330.0,
                  height: 267.0,
                  child: GeneratedRectangle9Widget(),
                )
              ]),
        ),
      ),
    ));
  }
}
