import 'package:flutter/material.dart';
import 'package:flutterapp/haiapp/generatedfilterframe3widget/generated/GeneratedBackWidget2.dart';
import 'package:flutterapp/haiapp/generatedfilterframe3widget/generated/GeneratedInputSearchWidget1.dart';
import 'package:flutterapp/haiapp/generatedfilterframe3widget/generated/GeneratedFilterModeWidget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';

/* Frame filter frame 3
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedFilterframe3Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        decoration: BoxDecoration(
          gradient: LinearGradient(
            begin: Alignment(0.0, -1.0),
            end: Alignment(0.0, 0.9999999999999998),
            stops: [0.0, 1.0],
            colors: [
              Color.fromARGB(255, 246, 243, 246),
              Color.fromARGB(0, 255, 255, 255)
            ],
          ),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              Positioned(
                left: null,
                top: 45.0,
                right: null,
                bottom: null,
                width: 179.0,
                height: 53.0,
                child: TransformHelper.translate(
                    x: -12.50,
                    y: 0.00,
                    z: 0,
                    child: GeneratedFilterModeWidget()),
              ),
              Positioned(
                left: 14.0,
                top: null,
                right: null,
                bottom: null,
                width: 43.0,
                height: 24.0,
                child: TransformHelper.translate(
                    x: 0.00, y: -384.00, z: 0, child: GeneratedBackWidget2()),
              ),
              Positioned(
                left: 31.0,
                top: null,
                right: 40.0,
                bottom: 600.0,
                width: null,
                height: 50.0,
                child: GeneratedInputSearchWidget1(),
              )
            ]),
      ),
    ));
  }
}
