import 'package:flutter/material.dart';
import 'package:flutterapp/haiapp/generatedcallingubframewidget/generated/GeneratedGroup4Widget.dart';

/* Frame Calling UB frame
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedCallingUBframeWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        decoration: BoxDecoration(
          gradient: LinearGradient(
            begin: Alignment(0.0, -1.0),
            end: Alignment(0.0, 0.9999999999999998),
            stops: [0.0, 1.0],
            colors: [
              Color.fromARGB(255, 246, 243, 246),
              Color.fromARGB(0, 255, 255, 255)
            ],
          ),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 426.0,
                height: 864.0,
                child: GeneratedGroup4Widget(),
              )
            ]),
      ),
    ));
  }
}
