import 'package:flutter/material.dart';
import 'package:flutterapp/haiapp/generatediphone11promax12widget/generated/GeneratedKeypadWidget1.dart';
import 'package:flutterapp/haiapp/generatediphone11promax12widget/generated/GeneratedBluetoothWidget1.dart';
import 'package:flutterapp/haiapp/generatediphone11promax12widget/generated/GeneratedOutgoingWidget1.dart';
import 'package:flutterapp/haiapp/generatediphone11promax12widget/generated/GeneratedMuteWidget1.dart';
import 'package:flutterapp/haiapp/generatediphone11promax12widget/generated/GeneratedHoldWidget1.dart';
import 'package:flutterapp/haiapp/generatediphone11promax12widget/generated/GeneratedCallWidget2.dart';
import 'package:flutterapp/haiapp/generatediphone11promax12widget/generated/GeneratedEndCallWidget1.dart';
import 'package:flutterapp/haiapp/generatediphone11promax12widget/generated/GeneratedAddWidget1.dart';
import 'package:flutterapp/haiapp/generatediphone11promax12widget/generated/GeneratedPauseWidget1.dart';
import 'package:flutterapp/haiapp/generatediphone11promax12widget/generated/GeneratedUBClinicWidget1.dart';
import 'package:flutterapp/haiapp/generatediphone11promax12widget/generated/GeneratedAddcallWidget1.dart';
import 'package:flutterapp/haiapp/generatediphone11promax12widget/generated/GeneratedVolume_upWidget1.dart';
import 'package:flutterapp/haiapp/generatediphone11promax12widget/generated/GeneratedMic_offWidget1.dart';
import 'package:flutterapp/haiapp/generatediphone11promax12widget/generated/GeneratedPhone_bluetooth_speakerWidget1.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/haiapp/generatediphone11promax12widget/generated/GeneratedCall_endWidget1.dart';
import 'package:flutterapp/haiapp/generatediphone11promax12widget/generated/GeneratedDialpadWidget1.dart';
import 'package:flutterapp/haiapp/generatediphone11promax12widget/generated/GeneratedSpeakerWidget1.dart';
import 'package:flutterapp/haiapp/generatediphone11promax12widget/generated/GeneratedRectangle8Widget6.dart';
import 'package:flutterapp/haiapp/generatediphone11promax12widget/generated/GeneratedHotlineWidget1.dart';

/* Frame iPhone 11 Pro Max - 12
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProMax12Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Visibility(
      visible: false,
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Container(
          width: 414.0,
          height: 896.0,
          child: Stack(
              fit: StackFit.expand,
              alignment: Alignment.center,
              overflow: Overflow.visible,
              children: [
                ClipRRect(
                  borderRadius: BorderRadius.zero,
                  child: Container(
                    color: Color.fromARGB(255, 183, 169, 201),
                  ),
                ),
                Positioned(
                  left: 0.000244140625,
                  top: 148.0,
                  right: null,
                  bottom: null,
                  width: 414.0007629394531,
                  height: 747.7596435546875,
                  child: GeneratedRectangle8Widget6(),
                ),
                Positioned(
                  left: 30.0,
                  top: 424.0,
                  right: null,
                  bottom: null,
                  width: 96.0,
                  height: 96.0,
                  child: GeneratedAddWidget1(),
                ),
                Positioned(
                  left: 289.0,
                  top: 424.0,
                  right: null,
                  bottom: null,
                  width: 96.0,
                  height: 96.0,
                  child: GeneratedPhone_bluetooth_speakerWidget1(),
                ),
                Positioned(
                  left: 30.0,
                  top: 580.0,
                  right: null,
                  bottom: null,
                  width: 96.0,
                  height: 96.0,
                  child: GeneratedVolume_upWidget1(),
                ),
                Positioned(
                  left: 160.0,
                  top: 580.0,
                  right: null,
                  bottom: null,
                  width: 96.0,
                  height: 96.0,
                  child: GeneratedMic_offWidget1(),
                ),
                Positioned(
                  left: 160.0,
                  top: 424.0,
                  right: null,
                  bottom: null,
                  width: 96.0,
                  height: 96.0,
                  child: GeneratedPauseWidget1(),
                ),
                Positioned(
                  left: 0.0,
                  top: 0.0,
                  right: 0.0,
                  bottom: 0.0,
                  width: null,
                  height: null,
                  child: LayoutBuilder(builder:
                      (BuildContext context, BoxConstraints constraints) {
                    final double width =
                        constraints.maxWidth * 0.10386473429951691;

                    final double height =
                        constraints.maxHeight * 0.03459821428571429;

                    return Stack(children: [
                      TransformHelper.translate(
                          x: constraints.maxWidth * 0.47342995169082125,
                          y: constraints.maxHeight * 0.5837053571428571,
                          z: 0,
                          child: Container(
                            width: width,
                            height: height,
                            child: GeneratedHoldWidget1(),
                          ))
                    ]);
                  }),
                ),
                Positioned(
                  left: 289.0,
                  top: 580.0,
                  right: null,
                  bottom: null,
                  width: 96.0,
                  height: 96.0,
                  child: GeneratedDialpadWidget1(),
                ),
                Positioned(
                  left: 160.0,
                  top: 721.0,
                  right: null,
                  bottom: null,
                  width: 96.0,
                  height: 68.0,
                  child: GeneratedCall_endWidget1(),
                ),
                Positioned(
                  left: 47.0,
                  top: 523.0,
                  right: null,
                  bottom: null,
                  width: 70.0,
                  height: 20.0,
                  child: GeneratedAddcallWidget1(),
                ),
                Positioned(
                  left: 301.0,
                  top: 521.0,
                  right: null,
                  bottom: null,
                  width: 77.0,
                  height: 23.0,
                  child: GeneratedBluetoothWidget1(),
                ),
                Positioned(
                  left: 52.0,
                  top: 676.0,
                  right: null,
                  bottom: null,
                  width: 64.0,
                  height: 33.0,
                  child: GeneratedSpeakerWidget1(),
                ),
                Positioned(
                  left: 189.0,
                  top: 680.0,
                  right: null,
                  bottom: null,
                  width: 43.0,
                  height: 24.0,
                  child: GeneratedMuteWidget1(),
                ),
                Positioned(
                  left: 317.0,
                  top: 680.0,
                  right: null,
                  bottom: null,
                  width: 57.0,
                  height: 24.0,
                  child: GeneratedKeypadWidget1(),
                ),
                Positioned(
                  left: 179.0,
                  top: 789.0,
                  right: null,
                  bottom: null,
                  width: 61.0,
                  height: 21.0,
                  child: GeneratedEndCallWidget1(),
                ),
                Positioned(
                  left: 115.0,
                  top: 154.0,
                  right: null,
                  bottom: null,
                  width: 177.0,
                  height: 49.0,
                  child: GeneratedUBClinicWidget1(),
                ),
                Positioned(
                  left: 136.0,
                  top: 38.0,
                  right: null,
                  bottom: null,
                  width: 24.0,
                  height: 24.0,
                  child: GeneratedCallWidget2(),
                ),
                Positioned(
                  left: 168.0,
                  top: 41.0,
                  right: null,
                  bottom: null,
                  width: 69.0,
                  height: 24.0,
                  child: GeneratedOutgoingWidget1(),
                ),
                Positioned(
                  left: 161.0,
                  top: 212.0,
                  right: null,
                  bottom: null,
                  width: 56.0,
                  height: 21.0,
                  child: GeneratedHotlineWidget1(),
                )
              ]),
        ),
      ),
    ));
  }
}
