import 'package:flutter/material.dart';
import 'package:flutterapp/haiapp/generatediphone11promax5widget/generated/GeneratedCardoutlineWidget1.dart';
import 'package:flutterapp/haiapp/generatediphone11promax5widget/generated/GeneratedRectangle8Widget8.dart';
import 'package:flutterapp/haiapp/generatediphone11promax5widget/generated/GeneratedCardoutlineWidget.dart';

/* Frame iPhone 11 Pro Max - 5
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProMax5Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Visibility(
      visible: false,
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Container(
          width: 414.0,
          height: 805.0,
          child: Stack(
              fit: StackFit.expand,
              alignment: Alignment.center,
              overflow: Overflow.visible,
              children: [
                ClipRRect(
                  borderRadius: BorderRadius.zero,
                  child: Container(
                    color: Color.fromARGB(255, 183, 169, 201),
                  ),
                ),
                Positioned(
                  left: -10.0,
                  top: 460.0,
                  right: null,
                  bottom: null,
                  width: 424.0,
                  height: 225.0,
                  child: GeneratedCardoutlineWidget(),
                ),
                Positioned(
                  left: -10.0,
                  top: 223.0,
                  right: null,
                  bottom: null,
                  width: 424.0,
                  height: 225.0,
                  child: GeneratedCardoutlineWidget1(),
                ),
                Positioned(
                  left: 0.000244140625,
                  top: 148.0,
                  right: null,
                  bottom: null,
                  width: 414.0007629394531,
                  height: 747.7596435546875,
                  child: GeneratedRectangle8Widget8(),
                )
              ]),
        ),
      ),
    ));
  }
}
