import 'package:flutter/material.dart';
import 'package:flutterapp/haiapp/generatediphone11promax15widget/generated/GeneratedScheduleWidget1.dart';
import 'package:flutterapp/haiapp/generatediphone11promax15widget/generated/GeneratedUpdatesWidget.dart';
import 'package:flutterapp/haiapp/generatediphone11promax15widget/generated/GeneratedVectorWidget26.dart';
import 'package:flutterapp/haiapp/generatediphone11promax15widget/generated/GeneratedEventsWidget.dart';
import 'package:flutterapp/haiapp/generatediphone11promax15widget/generated/GeneratedCovi19alertsWidget.dart';
import 'package:flutterapp/haiapp/generatediphone11promax15widget/generated/GeneratedFeelingSickWidget.dart';
import 'package:flutterapp/haiapp/generatediphone11promax15widget/generated/GeneratedRectangle8Widget3.dart';
import 'package:flutterapp/haiapp/generatediphone11promax15widget/generated/Generated202100546Widget.dart';
import 'package:flutterapp/haiapp/generatediphone11promax15widget/generated/GeneratedGroupWidget.dart';
import 'package:flutterapp/haiapp/generatediphone11promax15widget/generated/GeneratedScheduleWidget.dart';
import 'package:flutterapp/haiapp/generatediphone11promax15widget/generated/GeneratedPhoneWidget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/haiapp/generatediphone11promax15widget/generated/GeneratedNotifications_activeWidget.dart';
import 'package:flutterapp/haiapp/generatediphone11promax15widget/generated/GeneratedVectorWidget27.dart';

/* Frame iPhone 11 Pro Max - 15
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProMax15Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Visibility(
      visible: false,
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Container(
          width: 414.0,
          height: 896.0,
          child: Stack(
              fit: StackFit.expand,
              alignment: Alignment.center,
              overflow: Overflow.visible,
              children: [
                ClipRRect(
                  borderRadius: BorderRadius.zero,
                  child: Container(
                    color: Color.fromARGB(255, 183, 169, 201),
                  ),
                ),
                Positioned(
                  left: 0.000244140625,
                  top: 148.0,
                  right: null,
                  bottom: null,
                  width: 414.0007629394531,
                  height: 747.7596435546875,
                  child: GeneratedRectangle8Widget3(),
                ),
                Positioned(
                  left: 67.0,
                  top: 476.0,
                  right: null,
                  bottom: null,
                  width: 96.0,
                  height: 96.0,
                  child: GeneratedNotifications_activeWidget(),
                ),
                Positioned(
                  left: 245.0,
                  top: 476.0,
                  right: null,
                  bottom: null,
                  width: 96.0,
                  height: 96.0,
                  child: GeneratedGroupWidget(),
                ),
                Positioned(
                  left: 241.0,
                  top: 572.0,
                  right: null,
                  bottom: null,
                  width: 172.0,
                  height: 67.0,
                  child: GeneratedEventsWidget(),
                ),
                Positioned(
                  left: 35.0,
                  top: 576.0,
                  right: null,
                  bottom: null,
                  width: 166.0,
                  height: 71.0,
                  child: GeneratedUpdatesWidget(),
                ),
                Positioned(
                  left: 118.0,
                  top: 423.0,
                  right: null,
                  bottom: null,
                  width: 172.0,
                  height: 52.0,
                  child: GeneratedScheduleWidget(),
                ),
                Positioned(
                  left: 57.0,
                  top: 634.0,
                  right: null,
                  bottom: null,
                  width: 96.0,
                  height: 96.0,
                  child: GeneratedPhoneWidget(),
                ),
                Positioned(
                  left: 0.0,
                  top: 0.0,
                  right: 0.0,
                  bottom: 0.0,
                  width: null,
                  height: null,
                  child: LayoutBuilder(builder:
                      (BuildContext context, BoxConstraints constraints) {
                    double percentWidth = 0.15458937198067632;
                    double scaleX =
                        (constraints.maxWidth * percentWidth) / 64.0;

                    double percentHeight = 0.08705357142857142;
                    double scaleY =
                        (constraints.maxHeight * percentHeight) / 78.0;

                    return Stack(children: [
                      TransformHelper.translateAndScale(
                          translateX: constraints.maxWidth * 0.6183574879227053,
                          translateY:
                              constraints.maxHeight * 0.7243303571428571,
                          translateZ: 0,
                          scaleX: scaleX,
                          scaleY: scaleY,
                          scaleZ: 1,
                          child: GeneratedVectorWidget26())
                    ]);
                  }),
                ),
                Positioned(
                  left: 68.401611328125,
                  top: 727.0,
                  right: null,
                  bottom: null,
                  width: 142.0,
                  height: 15.0,
                  child: GeneratedFeelingSickWidget(),
                ),
                Positioned(
                  left: 239.0,
                  top: 730.0,
                  right: null,
                  bottom: null,
                  width: 164.0,
                  height: 65.0,
                  child: GeneratedCovi19alertsWidget(),
                ),
                Positioned(
                  left: 74.0,
                  top: 213.0,
                  right: null,
                  bottom: null,
                  width: 268.0,
                  height: 66.0,
                  child: Generated202100546Widget(),
                ),
                Positioned(
                  left: 0.0,
                  top: 0.0,
                  right: 0.0,
                  bottom: 0.0,
                  width: null,
                  height: null,
                  child: LayoutBuilder(builder:
                      (BuildContext context, BoxConstraints constraints) {
                    double percentWidth = 0.28743961352657005;
                    double scaleX =
                        (constraints.maxWidth * percentWidth) / 119.0;

                    double percentHeight = 0.13392857142857142;
                    double scaleY =
                        (constraints.maxHeight * percentHeight) / 120.0;

                    return Stack(children: [
                      TransformHelper.translateAndScale(
                          translateX:
                              constraints.maxWidth * 0.35507246376811596,
                          translateY:
                              constraints.maxHeight * 0.07477678571428571,
                          translateZ: 0,
                          scaleX: scaleX,
                          scaleY: scaleY,
                          scaleZ: 1,
                          child: GeneratedVectorWidget27())
                    ]);
                  }),
                ),
                Positioned(
                  left: 148.0,
                  top: 336.0,
                  right: null,
                  bottom: null,
                  width: 96.0,
                  height: 96.0,
                  child: GeneratedScheduleWidget1(),
                )
              ]),
        ),
      ),
    ));
  }
}
