import 'package:flutter/material.dart';
import 'package:flutterapp/haiapp/generatediphone11promax20widget/generated/GeneratedAdministratorWidget.dart';
import 'package:flutterapp/haiapp/generatediphone11promax20widget/generated/GeneratedMon211Widget.dart';
import 'package:flutterapp/haiapp/generatediphone11promax20widget/generated/GeneratedThu1023PMWidget.dart';
import 'package:flutterapp/haiapp/generatediphone11promax20widget/generated/GeneratedAttach_fileWidget1.dart';
import 'package:flutterapp/haiapp/generatediphone11promax20widget/generated/GeneratedAttach_fileWidget.dart';
import 'package:flutterapp/haiapp/generatediphone11promax20widget/generated/GeneratedLine27Widget.dart';
import 'package:flutterapp/haiapp/generatediphone11promax20widget/generated/GeneratedAdministratorWidget1.dart';
import 'package:flutterapp/haiapp/generatediphone11promax20widget/generated/GeneratedUBSRCElectionsWidget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/haiapp/generatediphone11promax20widget/generated/GeneratedEVENTSWidget.dart';
import 'package:flutterapp/haiapp/generatediphone11promax20widget/generated/GeneratedLine28Widget.dart';
import 'package:flutterapp/haiapp/generatediphone11promax20widget/generated/GeneratedEventcancelledWidget.dart';
import 'package:flutterapp/haiapp/generatediphone11promax20widget/generated/GeneratedVectorWidget6.dart';
import 'package:flutterapp/haiapp/generatediphone11promax20widget/generated/GeneratedAccount_circleWidget2.dart';
import 'package:flutterapp/haiapp/generatediphone11promax20widget/generated/GeneratedTue123Widget.dart';
import 'package:flutterapp/haiapp/generatediphone11promax20widget/generated/GeneratedVectorWidget17.dart';
import 'package:flutterapp/haiapp/generatediphone11promax20widget/generated/GeneratedAccount_circleWidget3.dart';
import 'package:flutterapp/haiapp/generatediphone11promax20widget/generated/GeneratedLine26Widget.dart';
import 'package:flutterapp/haiapp/generatediphone11promax20widget/generated/GeneratedMRANDMISSUB2021Widget.dart';
import 'package:flutterapp/haiapp/generatediphone11promax20widget/generated/GeneratedAttach_fileWidget2.dart';
import 'package:flutterapp/haiapp/generatediphone11promax20widget/generated/GeneratedAdministratorWidget2.dart';
import 'package:flutterapp/haiapp/generatediphone11promax20widget/generated/GeneratedGraduationCeremonyWidget.dart';
import 'package:flutterapp/haiapp/generatediphone11promax20widget/generated/GeneratedFri1430PMWidget.dart';
import 'package:flutterapp/haiapp/generatediphone11promax20widget/generated/GeneratedRectangle26Widget.dart';
import 'package:flutterapp/haiapp/generatediphone11promax20widget/generated/GeneratedRectangle8Widget1.dart';
import 'package:flutterapp/haiapp/generatediphone11promax20widget/generated/GeneratedAccount_circleWidget4.dart';
import 'package:flutterapp/haiapp/generatediphone11promax20widget/generated/GeneratedCsi4682021Widget.dart';

/* Frame iPhone 11 Pro Max - 20
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProMax20Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Visibility(
      visible: false,
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: LayoutBuilder(
            builder: (BuildContext context, BoxConstraints constraints) {
          return SingleChildScrollView(
            scrollDirection: Axis.vertical,
            child: Container(
                height: 905.0,
                child: Stack(children: [
                  Container(
                      width: constraints.maxWidth,
                      child: Container(
                        width: 525.0,
                        height: 905.0,
                        child: Stack(
                            fit: StackFit.expand,
                            alignment: Alignment.center,
                            overflow: Overflow.visible,
                            children: [
                              ClipRRect(
                                borderRadius: BorderRadius.zero,
                                child: Container(
                                  color: Color.fromARGB(255, 183, 169, 201),
                                ),
                              ),
                              Positioned(
                                left: 0.0,
                                top: 176.0,
                                right: null,
                                bottom: null,
                                width: 525.0,
                                height: 729.0,
                                child: GeneratedRectangle8Widget1(),
                              ),
                              Positioned(
                                left: 165.0,
                                top: 68.0,
                                right: null,
                                bottom: null,
                                width: 153.0,
                                height: 52.0,
                                child: GeneratedEVENTSWidget(),
                              ),
                              Positioned(
                                left: 0.0,
                                top: 176.0,
                                right: null,
                                bottom: null,
                                width: 525.0,
                                height: 729.0,
                                child: GeneratedRectangle26Widget(),
                              ),
                              Positioned(
                                left: 0.0,
                                top: 371.0,
                                right: null,
                                bottom: null,
                                width: 525.0009765625,
                                height: 1.0,
                                child: GeneratedLine26Widget(),
                              ),
                              Positioned(
                                left: 0.0,
                                top: 549.0,
                                right: null,
                                bottom: null,
                                width: 525.0,
                                height: 1.0,
                                child: GeneratedLine27Widget(),
                              ),
                              Positioned(
                                left: -1.0,
                                top: 719.0,
                                right: null,
                                bottom: null,
                                width: 526.0,
                                height: 1.0,
                                child: GeneratedLine28Widget(),
                              ),
                              Positioned(
                                left: 0.0,
                                top: 0.0,
                                right: 0.0,
                                bottom: 0.0,
                                width: null,
                                height: null,
                                child: LayoutBuilder(builder:
                                    (BuildContext context,
                                        BoxConstraints constraints) {
                                  double percentWidth = 0.1523809523809524;
                                  double scaleX =
                                      (constraints.maxWidth * percentWidth) /
                                          80.0;

                                  double percentHeight = 0.08839779005524862;
                                  double scaleY =
                                      (constraints.maxHeight * percentHeight) /
                                          80.0;

                                  return Stack(children: [
                                    TransformHelper.translateAndScale(
                                        translateX: constraints.maxWidth *
                                            0.015238095238095238,
                                        translateY: constraints.maxHeight *
                                            0.261878453038674,
                                        translateZ: 0,
                                        scaleX: scaleX,
                                        scaleY: scaleY,
                                        scaleZ: 1,
                                        child: GeneratedVectorWidget6())
                                  ]);
                                }),
                              ),
                              Positioned(
                                left: 0.0,
                                top: 424.0,
                                right: null,
                                bottom: null,
                                width: 96.0,
                                height: 96.0,
                                child: GeneratedAccount_circleWidget2(),
                              ),
                              Positioned(
                                left: 8.0,
                                top: 588.0,
                                right: null,
                                bottom: null,
                                width: 96.0,
                                height: 96.0,
                                child: GeneratedAccount_circleWidget3(),
                              ),
                              Positioned(
                                left: 16.0,
                                top: 764.0,
                                right: null,
                                bottom: null,
                                width: 96.0,
                                height: 96.0,
                                child: GeneratedAccount_circleWidget4(),
                              ),
                              Positioned(
                                left: 96.0,
                                top: 200.0,
                                right: null,
                                bottom: null,
                                width: 289.0,
                                height: 62.0,
                                child: GeneratedAdministratorWidget(),
                              ),
                              Positioned(
                                left: 431.0,
                                top: 215.0,
                                right: null,
                                bottom: null,
                                width: 141.0,
                                height: 37.0,
                                child: GeneratedFri1430PMWidget(),
                              ),
                              Positioned(
                                left: 132.0,
                                top: 257.0,
                                right: null,
                                bottom: null,
                                width: 250.0,
                                height: 46.0,
                                child: GeneratedUBSRCElectionsWidget(),
                              ),
                              Positioned(
                                left: 104.0,
                                top: 394.0,
                                right: null,
                                bottom: null,
                                width: 256.0,
                                height: 35.0,
                                child: GeneratedAdministratorWidget1(),
                              ),
                              Positioned(
                                left: 430.0,
                                top: 410.0,
                                right: null,
                                bottom: null,
                                width: 156.0,
                                height: 75.0,
                                child: GeneratedThu1023PMWidget(),
                              ),
                              Positioned(
                                left: 132.0,
                                top: 452.0,
                                right: null,
                                bottom: null,
                                width: 211.0,
                                height: 39.0,
                                child: GeneratedMRANDMISSUB2021Widget(),
                              ),
                              Positioned(
                                left: 136.0,
                                top: 569.0,
                                right: null,
                                bottom: null,
                                width: 238.0,
                                height: 40.0,
                                child: GeneratedCsi4682021Widget(),
                              ),
                              Positioned(
                                left: 148.0,
                                top: 638.0,
                                right: null,
                                bottom: null,
                                width: 234.0,
                                height: 36.0,
                                child: GeneratedEventcancelledWidget(),
                              ),
                              Positioned(
                                left: 455.0,
                                top: 583.0,
                                right: null,
                                bottom: null,
                                width: 106.0,
                                height: 17.0,
                                child: GeneratedMon211Widget(),
                              ),
                              Positioned(
                                left: 476.0,
                                top: 382.0,
                                right: null,
                                bottom: null,
                                width: 24.0,
                                height: 24.0,
                                child: GeneratedAttach_fileWidget(),
                              ),
                              Positioned(
                                left: 464.0,
                                top: 188.0,
                                right: null,
                                bottom: null,
                                width: 24.0,
                                height: 24.0,
                                child: GeneratedAttach_fileWidget1(),
                              ),
                              Positioned(
                                left: 0.0,
                                top: 0.0,
                                right: 0.0,
                                bottom: 0.0,
                                width: null,
                                height: null,
                                child: LayoutBuilder(builder:
                                    (BuildContext context,
                                        BoxConstraints constraints) {
                                  double percentWidth = 0.02095238095238095;
                                  double scaleX =
                                      (constraints.maxWidth * percentWidth) /
                                          11.0;

                                  double percentHeight = 0.02430939226519337;
                                  double scaleY =
                                      (constraints.maxHeight * percentHeight) /
                                          22.0;

                                  return Stack(children: [
                                    TransformHelper.translateAndScale(
                                        translateX: constraints.maxWidth * 0.92,
                                        translateY: constraints.maxHeight *
                                            0.6121546961325967,
                                        translateZ: 0,
                                        scaleX: scaleX,
                                        scaleY: scaleY,
                                        scaleZ: 1,
                                        child: GeneratedVectorWidget17())
                                  ]);
                                }),
                              ),
                              Positioned(
                                left: 483.0,
                                top: 741.0,
                                right: null,
                                bottom: null,
                                width: 24.0,
                                height: 24.0,
                                child: GeneratedAttach_fileWidget2(),
                              ),
                              Positioned(
                                left: 465.0,
                                top: 780.0,
                                right: null,
                                bottom: null,
                                width: 62.0,
                                height: 26.0,
                                child: GeneratedTue123Widget(),
                              ),
                              Positioned(
                                left: 153.0,
                                top: 748.0,
                                right: null,
                                bottom: null,
                                width: 257.0,
                                height: 37.0,
                                child: GeneratedAdministratorWidget2(),
                              ),
                              Positioned(
                                left: 156.0,
                                top: 816.0,
                                right: null,
                                bottom: null,
                                width: 246.0,
                                height: 38.0,
                                child: GeneratedGraduationCeremonyWidget(),
                              )
                            ]),
                      ))
                ])),
          );
        }),
      ),
    ));
  }
}
