import 'package:flutter/material.dart';
import 'package:flutterapp/haiapp/generatedcovid19alertsframewidget/generated/GeneratedButtonPrimaryWidget3.dart';
import 'package:flutterapp/haiapp/generatedcovid19alertsframewidget/generated/GeneratedButtonPrimaryWidget2.dart';
import 'package:flutterapp/haiapp/generatedcovid19alertsframewidget/generated/GeneratedPageHeaderWidget1.dart';
import 'package:flutterapp/haiapp/generatedcovid19alertsframewidget/generated/GeneratedButtonPrimaryWidget1.dart';

/* Frame Covid 19 alerts frame
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedCovid19alertsframeWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        decoration: BoxDecoration(
          gradient: LinearGradient(
            begin: Alignment(0.0, -1.0),
            end: Alignment(0.0, 0.9999999999999998),
            stops: [0.0, 1.0],
            colors: [
              Color.fromARGB(255, 246, 243, 246),
              Color.fromARGB(0, 255, 255, 255)
            ],
          ),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              Positioned(
                left: 20.0,
                top: 67.0,
                right: 51.0,
                bottom: null,
                width: null,
                height: 38.0,
                child: GeneratedPageHeaderWidget1(),
              ),
              Positioned(
                left: 36.0,
                top: null,
                right: 35.0,
                bottom: 407.0,
                width: null,
                height: 68.0,
                child: GeneratedButtonPrimaryWidget1(),
              ),
              Positioned(
                left: 36.0,
                top: null,
                right: 35.0,
                bottom: 515.0,
                width: null,
                height: 68.0,
                child: GeneratedButtonPrimaryWidget2(),
              ),
              Positioned(
                left: 36.0,
                top: null,
                right: 35.0,
                bottom: 299.0,
                width: null,
                height: 68.0,
                child: GeneratedButtonPrimaryWidget3(),
              )
            ]),
      ),
    ));
  }
}
