import 'package:flutter/material.dart';
import 'package:flutterapp/haiapp/generatedmessagesframewidget/generated/GeneratedBackWidget1.dart';
import 'package:flutterapp/haiapp/generatedmessagesframewidget/generated/GeneratedMessageReceiveWidget.dart';
import 'package:flutterapp/haiapp/generatedmessagesframewidget/generated/GeneratedInputSearchWidget.dart';
import 'package:flutterapp/haiapp/generatedmessagesframewidget/generated/GeneratedMessagesWidget1.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/haiapp/generatedmessagesframewidget/generated/GeneratedMessageSendWidget.dart';
import 'package:flutterapp/haiapp/generatedmessagesframewidget/generated/GeneratedFilterWidget.dart';

/* Frame Messages frame
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedMessagesframeWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        decoration: BoxDecoration(
          gradient: LinearGradient(
            begin: Alignment(0.0, -1.0),
            end: Alignment(0.0, 0.9999999999999998),
            stops: [0.0, 1.0],
            colors: [
              Color.fromARGB(255, 246, 243, 246),
              Color.fromARGB(0, 255, 255, 255)
            ],
          ),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              Positioned(
                left: null,
                top: 45.0,
                right: null,
                bottom: null,
                width: 154.0,
                height: 56.0,
                child: TransformHelper.translate(
                    x: 3.00, y: 0.00, z: 0, child: GeneratedMessagesWidget1()),
              ),
              Positioned(
                left: null,
                top: 52.0,
                right: 11.0,
                bottom: null,
                width: 44.0,
                height: 24.0,
                child: GeneratedFilterWidget(),
              ),
              Positioned(
                left: 14.0,
                top: null,
                right: null,
                bottom: null,
                width: 43.0,
                height: 24.0,
                child: TransformHelper.translate(
                    x: 0.00, y: -384.00, z: 0, child: GeneratedBackWidget1()),
              ),
              Positioned(
                left: 15.0,
                top: 185.0,
                right: null,
                bottom: null,
                width: 235.0,
                height: 126.0,
                child: GeneratedMessageReceiveWidget(),
              ),
              Positioned(
                left: null,
                top: 333.0,
                right: 16.0,
                bottom: null,
                width: 235.0,
                height: 86.0,
                child: GeneratedMessageSendWidget(),
              ),
              Positioned(
                left: 39.0,
                top: null,
                right: 32.0,
                bottom: 41.0,
                width: null,
                height: 50.0,
                child: GeneratedInputSearchWidget(),
              )
            ]),
      ),
    ));
  }
}
