import 'package:flutter/material.dart';
import 'package:flutterapp/haiapp/generatediphone11promax11widget/generated/GeneratedRectangle8Widget7.dart';
import 'package:flutterapp/haiapp/generatediphone11promax11widget/generated/GeneratedCheckmarkWidget1.dart';
import 'package:flutterapp/haiapp/generatediphone11promax11widget/generated/GeneratedRESULTSWidget.dart';
import 'package:flutterapp/haiapp/generatediphone11promax11widget/generated/GeneratedCheckmarkWidget2.dart';
import 'package:flutterapp/haiapp/generatediphone11promax11widget/generated/GeneratedNEGATIVEWidget1.dart';

/* Frame iPhone 11 Pro Max - 11
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProMax11Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Visibility(
      visible: false,
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Container(
          width: 414.0,
          height: 896.0,
          child: Stack(
              fit: StackFit.expand,
              alignment: Alignment.center,
              overflow: Overflow.visible,
              children: [
                ClipRRect(
                  borderRadius: BorderRadius.zero,
                  child: Container(
                    color: Color.fromARGB(255, 183, 169, 201),
                  ),
                ),
                Positioned(
                  left: 0.000244140625,
                  top: 148.0,
                  right: null,
                  bottom: null,
                  width: 414.0007629394531,
                  height: 747.7596435546875,
                  child: GeneratedRectangle8Widget7(),
                ),
                Positioned(
                  left: 82.0,
                  top: 188.0,
                  right: null,
                  bottom: null,
                  width: 254.0,
                  height: 75.0,
                  child: GeneratedRESULTSWidget(),
                ),
                Positioned(
                  left: 113.0,
                  top: 401.0,
                  right: null,
                  bottom: null,
                  width: 193.0,
                  height: 52.0,
                  child: GeneratedNEGATIVEWidget1(),
                ),
                Positioned(
                  left: 109.0,
                  top: 656.0,
                  right: null,
                  bottom: null,
                  width: 192.0,
                  height: 192.0,
                  child: GeneratedCheckmarkWidget1(),
                ),
                Positioned(
                  left: 195.0,
                  top: 510.0,
                  right: null,
                  bottom: null,
                  width: 24.0,
                  height: 24.0,
                  child: GeneratedCheckmarkWidget2(),
                )
              ]),
        ),
      ),
    ));
  }
}
