import 'package:flutter/material.dart';
import 'package:flutterapp/haiapp/generatedfeedframewidget/generated/GeneratedContentBlocksWidget.dart';
import 'package:flutterapp/haiapp/generatedfeedframewidget/generated/GeneratedPageHeaderWidget8.dart';
import 'package:flutterapp/haiapp/generatedfeedframewidget/generated/GeneratedInputSearchWidget2.dart';
import 'package:flutterapp/haiapp/generatedfeedframewidget/generated/GeneratedIOSBottomBar5TabsWidget.dart';

/* Frame Feed frame
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedFeedframeWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        decoration: BoxDecoration(
          gradient: LinearGradient(
            begin: Alignment(0.0, -1.0),
            end: Alignment(0.0, 0.9999999999999998),
            stops: [0.0, 1.0],
            colors: [
              Color.fromARGB(255, 246, 243, 246),
              Color.fromARGB(0, 255, 255, 255)
            ],
          ),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              Positioned(
                left: 39.0,
                top: 51.0,
                right: 32.0,
                bottom: null,
                width: null,
                height: 36.0,
                child: GeneratedPageHeaderWidget8(),
              ),
              Positioned(
                left: 39.0,
                top: 155.0,
                right: 32.0,
                bottom: null,
                width: null,
                height: 50.0,
                child: GeneratedInputSearchWidget2(),
              ),
              Positioned(
                left: 39.0,
                top: 268.0,
                right: 32.0,
                bottom: null,
                width: null,
                height: 356.0000305175781,
                child: GeneratedContentBlocksWidget(),
              ),
              Positioned(
                left: 6.0,
                top: null,
                right: -6.0,
                bottom: 37.0,
                width: null,
                height: 81.0,
                child: GeneratedIOSBottomBar5TabsWidget(),
              )
            ]),
      ),
    ));
  }
}
