import 'package:flutter/material.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/haiapp/generatedloginframewidget/generated/GeneratedPageHeaderWidget.dart';
import 'package:flutterapp/haiapp/generatedloginframewidget/generated/GeneratedDontHaveanaccountWidget.dart';
import 'package:flutterapp/haiapp/generatedloginframewidget/generated/GeneratedInputTextWidget.dart';
import 'package:flutterapp/haiapp/generatedloginframewidget/generated/GeneratedInputTextWidget1.dart';
import 'package:flutterapp/haiapp/generatedloginframewidget/generated/GeneratedButtonPrimaryWidget.dart';
import 'package:flutterapp/haiapp/generatedloginframewidget/generated/GeneratedForgotyourpasswordWidget.dart';

/* Frame Login frame
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedLoginframeWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        decoration: BoxDecoration(
          gradient: LinearGradient(
            begin: Alignment(0.0, -1.0),
            end: Alignment(0.0, 0.9999999999999998),
            stops: [0.0, 1.0],
            colors: [
              Color.fromARGB(255, 246, 243, 246),
              Color.fromARGB(0, 255, 255, 255)
            ],
          ),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              Positioned(
                left: 36.0,
                top: 262.0,
                right: 35.0,
                bottom: null,
                width: null,
                height: 50.0,
                child: GeneratedInputTextWidget(),
              ),
              Positioned(
                left: 36.0,
                top: 375.0,
                right: 35.0,
                bottom: null,
                width: null,
                height: 50.0,
                child: GeneratedInputTextWidget1(),
              ),
              Positioned(
                left: 20.0,
                top: 67.0,
                right: 51.0,
                bottom: null,
                width: null,
                height: 38.0,
                child: GeneratedPageHeaderWidget(),
              ),
              Positioned(
                left: 36.0,
                top: null,
                right: 35.0,
                bottom: 336.0,
                width: null,
                height: 51.0,
                child: GeneratedButtonPrimaryWidget(),
              ),
              Positioned(
                left: null,
                top: null,
                right: null,
                bottom: 303.0,
                width: 180.0,
                height: 21.0,
                child: TransformHelper.translate(
                    x: 1.00,
                    y: 0.00,
                    z: 0,
                    child: GeneratedForgotyourpasswordWidget()),
              ),
              Positioned(
                left: null,
                top: null,
                right: null,
                bottom: 221.0,
                width: 181.0,
                height: 21.0,
                child: TransformHelper.translate(
                    x: 10.50,
                    y: 0.00,
                    z: 0,
                    child: GeneratedDontHaveanaccountWidget()),
              )
            ]),
      ),
    ));
  }
}
