import 'package:flutter/material.dart';
import 'package:flutterapp/haiapp/generatedpasswordresetframewidget/generated/GeneratedPageHeaderWidget4.dart';
import 'package:flutterapp/haiapp/generatedpasswordresetframewidget/generated/GeneratedInputTextWidget5.dart';
import 'package:flutterapp/haiapp/generatedpasswordresetframewidget/generated/GeneratedButtonPrimaryWidget7.dart';
import 'package:flutterapp/haiapp/generatedpasswordresetframewidget/generated/GeneratedInputTextWidget6.dart';
import 'package:flutterapp/haiapp/generatedpasswordresetframewidget/generated/GeneratedInputTextWidget7.dart';

/* Frame Password Reset frame
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedPasswordResetframeWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        decoration: BoxDecoration(
          gradient: LinearGradient(
            begin: Alignment(0.0, -1.0),
            end: Alignment(0.0, 0.9999999999999998),
            stops: [0.0, 1.0],
            colors: [
              Color.fromARGB(255, 246, 243, 246),
              Color.fromARGB(0, 255, 255, 255)
            ],
          ),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              Positioned(
                left: 36.0,
                top: 318.0,
                right: 35.0,
                bottom: null,
                width: null,
                height: 50.0,
                child: GeneratedInputTextWidget5(),
              ),
              Positioned(
                left: 36.0,
                top: 414.0,
                right: 35.0,
                bottom: null,
                width: null,
                height: 50.0,
                child: GeneratedInputTextWidget6(),
              ),
              Positioned(
                left: 20.0,
                top: 68.0,
                right: 51.0,
                bottom: null,
                width: null,
                height: 36.0,
                child: GeneratedPageHeaderWidget4(),
              ),
              Positioned(
                left: 42.0,
                top: 222.0,
                right: 29.0,
                bottom: null,
                width: null,
                height: 50.0,
                child: GeneratedInputTextWidget7(),
              ),
              Positioned(
                left: 36.0,
                top: null,
                right: 35.0,
                bottom: 300.0,
                width: null,
                height: 51.0,
                child: GeneratedButtonPrimaryWidget7(),
              )
            ]),
      ),
    ));
  }
}
