import 'package:flutter/material.dart';
import 'package:flutterapp/haiapp/generatediphone11promax17widget/generated/GeneratedAccount_circleWidget1.dart';
import 'package:flutterapp/haiapp/generatediphone11promax17widget/generated/GeneratedITAnnouncementPlannedNetworkMaintenaceDearAllYouareadvi.dart';
import 'package:flutterapp/haiapp/generatediphone11promax17widget/generated/Generated2622021Widget.dart';
import 'package:flutterapp/haiapp/generatediphone11promax17widget/generated/Generated2222021Widget.dart';
import 'package:flutterapp/haiapp/generatediphone11promax17widget/generated/GeneratedVectorWidget5.dart';
import 'package:flutterapp/haiapp/generatediphone11promax17widget/generated/GeneratedSearchWidget.dart';
import 'package:flutterapp/haiapp/generatediphone11promax17widget/generated/GeneratedSearchWidget1.dart';
import 'package:flutterapp/haiapp/generatediphone11promax17widget/generated/GeneratedRectangle8Widget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/haiapp/generatediphone11promax17widget/generated/GeneratedAdministratorDeathNoticeGoodDayitisagreatsorrowthattheu.dart';
import 'package:flutterapp/haiapp/generatediphone11promax17widget/generated/Generated2422021Widget1.dart';
import 'package:flutterapp/haiapp/generatediphone11promax17widget/generated/GeneratedVectorWidget4.dart';
import 'package:flutterapp/haiapp/generatediphone11promax17widget/generated/Generated2422021Widget.dart';
import 'package:flutterapp/haiapp/generatediphone11promax17widget/generated/GeneratedRectangle25Widget.dart';
import 'package:flutterapp/haiapp/generatediphone11promax17widget/generated/GeneratedAdministratorAdvertResidentAssistantPartTimeJobforstude.dart';
import 'package:flutterapp/haiapp/generatediphone11promax17widget/generated/GeneratedAccount_circleWidget.dart';
import 'package:flutterapp/haiapp/generatediphone11promax17widget/generated/GeneratedAdministratorSemesterBreak20202021DearStudentsWidget.dart';
import 'package:flutterapp/haiapp/generatediphone11promax17widget/generated/GeneratedUPDATESWidget.dart';

/* Frame iPhone 11 Pro Max - 17
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProMax17Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Visibility(
      visible: false,
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: LayoutBuilder(
            builder: (BuildContext context, BoxConstraints constraints) {
          return SingleChildScrollView(
            scrollDirection: Axis.vertical,
            child: Container(
                height: 950.0,
                child: Stack(children: [
                  Container(
                      width: constraints.maxWidth,
                      child: Container(
                        width: 525.0,
                        height: 905.0,
                        child: Stack(
                            fit: StackFit.expand,
                            alignment: Alignment.center,
                            overflow: Overflow.visible,
                            children: [
                              ClipRRect(
                                borderRadius: BorderRadius.zero,
                                child: Container(
                                  color: Color.fromARGB(255, 183, 169, 201),
                                ),
                              ),
                              Positioned(
                                left: 0.0,
                                top: 176.0,
                                right: null,
                                bottom: null,
                                width: 414.0007629394531,
                                height: 747.7596435546875,
                                child: GeneratedRectangle8Widget(),
                              ),
                              Positioned(
                                left: 152.0,
                                top: 76.0,
                                right: null,
                                bottom: null,
                                width: 180.0,
                                height: 52.0,
                                child: GeneratedUPDATESWidget(),
                              ),
                              Positioned(
                                left: 3.0,
                                top: 176.0,
                                right: null,
                                bottom: null,
                                width: 523.0,
                                height: 774.0,
                                child: GeneratedRectangle25Widget(),
                              ),
                              Positioned(
                                left: 84.0,
                                top: 563.0,
                                right: null,
                                bottom: null,
                                width: 338.0,
                                height: 106.0,
                                child:
                                    GeneratedAdministratorAdvertResidentAssistantPartTimeJobforstude(),
                              ),
                              Positioned(
                                left: 2.0,
                                top: 563.0,
                                right: null,
                                bottom: null,
                                width: 75.0,
                                height: 55.0,
                                child: GeneratedAccount_circleWidget(),
                              ),
                              Positioned(
                                left: 2.0,
                                top: 358.0,
                                right: null,
                                bottom: null,
                                width: 79.0,
                                height: 59.0,
                                child: GeneratedAccount_circleWidget1(),
                              ),
                              Positioned(
                                left: 80.0,
                                top: 366.0,
                                right: null,
                                bottom: null,
                                width: 320.0,
                                height: 169.0,
                                child:
                                    GeneratedITAnnouncementPlannedNetworkMaintenaceDearAllYouareadvi(),
                              ),
                              Positioned(
                                left: 0.0,
                                top: 0.0,
                                right: 0.0,
                                bottom: 0.0,
                                width: null,
                                height: null,
                                child: LayoutBuilder(builder:
                                    (BuildContext context,
                                        BoxConstraints constraints) {
                                  double percentWidth = 0.12278584798177083;
                                  double scaleX =
                                      (constraints.maxWidth * percentWidth) /
                                          64.46257019042969;

                                  double percentHeight = 0.05230881496029006;
                                  double scaleY =
                                      (constraints.maxHeight * percentHeight) /
                                          47.3394775390625;

                                  return Stack(children: [
                                    TransformHelper.translateAndScale(
                                        translateX: 0,
                                        translateY: constraints.maxHeight *
                                            0.2165745856353591,
                                        translateZ: 0,
                                        scaleX: scaleX,
                                        scaleY: scaleY,
                                        scaleZ: 1,
                                        child: GeneratedVectorWidget4())
                                  ]);
                                }),
                              ),
                              Positioned(
                                left: 84.0,
                                top: 183.0,
                                right: null,
                                bottom: null,
                                width: 291.0,
                                height: 158.0,
                                child:
                                    GeneratedAdministratorSemesterBreak20202021DearStudentsWidget(),
                              ),
                              Positioned(
                                left: 0.0,
                                top: 0.0,
                                right: 0.0,
                                bottom: 0.0,
                                width: null,
                                height: null,
                                child: LayoutBuilder(builder:
                                    (BuildContext context,
                                        BoxConstraints constraints) {
                                  double percentWidth = 0.12237093970889137;
                                  double scaleX =
                                      (constraints.maxWidth * percentWidth) /
                                          64.24474334716797;

                                  double percentHeight = 0.05150207182320442;
                                  double scaleY =
                                      (constraints.maxHeight * percentHeight) /
                                          46.609375;

                                  return Stack(children: [
                                    TransformHelper.translateAndScale(
                                        translateX: 0,
                                        translateY: constraints.maxHeight *
                                            0.7745856353591161,
                                        translateZ: 0,
                                        scaleX: scaleX,
                                        scaleY: scaleY,
                                        scaleZ: 1,
                                        child: GeneratedVectorWidget5())
                                  ]);
                                }),
                              ),
                              Positioned(
                                left: 411.0,
                                top: 300.0,
                                right: null,
                                bottom: null,
                                width: 120.0,
                                height: 44.0,
                                child: Generated2622021Widget(),
                              ),
                              Positioned(
                                left: 402.0,
                                top: 502.0,
                                right: null,
                                bottom: null,
                                width: 129.0,
                                height: 34.0,
                                child: Generated2422021Widget(),
                              ),
                              Positioned(
                                left: 401.0,
                                top: 645.0,
                                right: null,
                                bottom: null,
                                width: 129.0,
                                height: 35.0,
                                child: Generated2422021Widget1(),
                              ),
                              Positioned(
                                left: 443.0,
                                top: 27.0,
                                right: null,
                                bottom: null,
                                width: 62.0,
                                height: 56.0,
                                child: GeneratedSearchWidget(),
                              ),
                              Positioned(
                                left: 354.0,
                                top: 27.0,
                                right: null,
                                bottom: null,
                                width: 94.0,
                                height: 54.0,
                                child: GeneratedSearchWidget1(),
                              ),
                              Positioned(
                                left: 91.0,
                                top: 693.0,
                                right: null,
                                bottom: null,
                                width: 250.0,
                                height: 33.0,
                                child:
                                    GeneratedAdministratorDeathNoticeGoodDayitisagreatsorrowthattheu(),
                              ),
                              Positioned(
                                left: 406.0,
                                top: 855.0,
                                right: null,
                                bottom: null,
                                width: 129.0,
                                height: 35.0,
                                child: Generated2222021Widget(),
                              )
                            ]),
                      ))
                ])),
          );
        }),
      ),
    ));
  }
}
