import 'package:flutter/material.dart';
import 'package:flutterapp/haiapp/generatediphone11promax14widget/generated/GeneratedAreyouexperiencingtheanyorallsymptomsbelowWidget.dart';
import 'package:flutterapp/haiapp/generatediphone11promax14widget/generated/GeneratedCallWidget.dart';
import 'package:flutterapp/haiapp/generatediphone11promax14widget/generated/GeneratedSymptomsWidget.dart';
import 'package:flutterapp/haiapp/generatediphone11promax14widget/generated/GeneratedAccount_circleWidget5.dart';
import 'package:flutterapp/haiapp/generatediphone11promax14widget/generated/GeneratedFeverorchillsCoughShortnessofbreathordifficultybreathin.dart';
import 'package:flutterapp/haiapp/generatediphone11promax14widget/generated/GeneratedVideo_callWidget.dart';
import 'package:flutterapp/haiapp/generatediphone11promax14widget/generated/GeneratedRectangle16Widget.dart';
import 'package:flutterapp/haiapp/generatediphone11promax14widget/generated/GeneratedRectangle7Widget.dart';
import 'package:flutterapp/haiapp/generatediphone11promax14widget/generated/GeneratedRectangle8Widget4.dart';
import 'package:flutterapp/haiapp/generatediphone11promax14widget/generated/GeneratedCheckmarkWidget.dart';

/* Frame iPhone 11 Pro Max - 14
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProMax14Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Visibility(
      visible: false,
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Container(
          width: 414.0,
          height: 896.0,
          child: Stack(
              fit: StackFit.expand,
              alignment: Alignment.center,
              overflow: Overflow.visible,
              children: [
                ClipRRect(
                  borderRadius: BorderRadius.zero,
                  child: Container(
                    color: Color.fromARGB(255, 183, 169, 201),
                  ),
                ),
                Positioned(
                  left: 0.000244140625,
                  top: 148.0,
                  right: null,
                  bottom: null,
                  width: 414.0007629394531,
                  height: 747.7596435546875,
                  child: GeneratedRectangle8Widget4(),
                ),
                Positioned(
                  left: 12.0,
                  top: 240.5303955078125,
                  right: null,
                  bottom: null,
                  width: 387.0,
                  height: 566.467041015625,
                  child: GeneratedRectangle7Widget(),
                ),
                Positioned(
                  left: 77.0,
                  top: 370.0,
                  right: null,
                  bottom: null,
                  width: 293.0,
                  height: 421.0,
                  child:
                      GeneratedFeverorchillsCoughShortnessofbreathordifficultybreathin(),
                ),
                Positioned(
                  left: 77.0,
                  top: 307.0,
                  right: null,
                  bottom: null,
                  width: 228.0,
                  height: 40.0,
                  child:
                      GeneratedAreyouexperiencingtheanyorallsymptomsbelowWidget(),
                ),
                Positioned(
                  left: 77.0,
                  top: 256.0,
                  right: null,
                  bottom: null,
                  width: 201.0,
                  height: 56.0,
                  child: GeneratedSymptomsWidget(),
                ),
                Positioned(
                  left: 0.0,
                  top: -1.0,
                  right: null,
                  bottom: null,
                  width: 414.0,
                  height: 214.0,
                  child: GeneratedRectangle16Widget(),
                ),
                Positioned(
                  left: 12.0,
                  top: 37.0,
                  right: null,
                  bottom: null,
                  width: 135.0,
                  height: 119.0,
                  child: GeneratedAccount_circleWidget5(),
                ),
                Positioned(
                  left: 282.0,
                  top: 57.0,
                  right: null,
                  bottom: null,
                  width: 96.0,
                  height: 96.0,
                  child: GeneratedVideo_callWidget(),
                ),
                Positioned(
                  left: 147.0,
                  top: 57.0,
                  right: null,
                  bottom: null,
                  width: 96.0,
                  height: 96.0,
                  child: GeneratedCallWidget(),
                ),
                Positioned(
                  left: 303.0,
                  top: 789.0,
                  right: null,
                  bottom: null,
                  width: 86.0,
                  height: 96.0,
                  child: GeneratedCheckmarkWidget(),
                )
              ]),
        ),
      ),
    ));
  }
}
