import 'package:flutter/material.dart';
import 'package:flutterapp/haiapp/generatedhomeframewidget/generated/GeneratedContentMarketBlockWidget2.dart';
import 'package:flutterapp/haiapp/generatedhomeframewidget/generated/GeneratedContentMarketBlockWidget5.dart';
import 'package:flutterapp/haiapp/generatedhomeframewidget/generated/GeneratedPageHeaderWidget10.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/haiapp/generatedhomeframewidget/generated/GeneratedEllipse7Widget.dart';
import 'package:flutterapp/haiapp/generatedhomeframewidget/generated/GeneratedContentMarketBlockWidget4.dart';
import 'package:flutterapp/haiapp/generatedhomeframewidget/generated/GeneratedContentMarketBlockWidget3.dart';
import 'package:flutterapp/haiapp/generatedhomeframewidget/generated/GeneratedNameBioWidget.dart';
import 'package:flutterapp/haiapp/generatedhomeframewidget/generated/GeneratedIOSBottomBar5TabsWidget2.dart';
import 'package:flutterapp/haiapp/generatedhomeframewidget/generated/GeneratedRectangle240Widget.dart';

/* Frame Home frame
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedHomeframeWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        decoration: BoxDecoration(
          gradient: LinearGradient(
            begin: Alignment(0.0, -1.0),
            end: Alignment(0.0, 0.9999999999999998),
            stops: [0.0, 1.0],
            colors: [
              Color.fromARGB(255, 246, 243, 246),
              Color.fromARGB(0, 255, 255, 255)
            ],
          ),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              Positioned(
                left: 6.0,
                top: null,
                right: -6.0,
                bottom: 37.0,
                width: null,
                height: 81.0,
                child: GeneratedIOSBottomBar5TabsWidget2(),
              ),
              Positioned(
                left: -6.0,
                top: 0.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 266.0,
                child: GeneratedRectangle240Widget(),
              ),
              Positioned(
                left: 42.0,
                top: 51.0,
                right: 29.0,
                bottom: null,
                width: null,
                height: 36.0,
                child: GeneratedPageHeaderWidget10(),
              ),
              Positioned(
                left: null,
                top: 133.0,
                right: null,
                bottom: null,
                width: 158.0,
                height: 158.0,
                child: TransformHelper.translate(
                    x: 8.00, y: 0.00, z: 0, child: GeneratedEllipse7Widget()),
              ),
              Positioned(
                left: 112.0,
                top: 325.0,
                right: null,
                bottom: null,
                width: 190.0,
                height: 63.0,
                child: GeneratedNameBioWidget(),
              ),
              Positioned(
                left: 57.0,
                top: 414.0,
                right: null,
                bottom: null,
                width: 110.0,
                height: 177.0,
                child: GeneratedContentMarketBlockWidget2(),
              ),
              Positioned(
                left: 57.0,
                top: 591.0,
                right: null,
                bottom: null,
                width: 110.0,
                height: 177.0,
                child: GeneratedContentMarketBlockWidget3(),
              ),
              Positioned(
                left: 221.0,
                top: 414.0,
                right: null,
                bottom: null,
                width: 110.0,
                height: 177.0,
                child: GeneratedContentMarketBlockWidget4(),
              ),
              Positioned(
                left: 224.0,
                top: 591.0,
                right: null,
                bottom: null,
                width: 110.0,
                height: 177.0,
                child: GeneratedContentMarketBlockWidget5(),
              )
            ]),
      ),
    ));
  }
}
