import 'package:flutter/material.dart';
import 'package:flutterapp/haiapp/generatediphone11promax19widget/generated/GeneratedLine11Widget.dart';
import 'package:flutterapp/haiapp/generatediphone11promax19widget/generated/GeneratedAddEditWidget.dart';
import 'package:flutterapp/haiapp/generatediphone11promax19widget/generated/GeneratedEventReminderWidget.dart';
import 'package:flutterapp/haiapp/generatediphone11promax19widget/generated/GeneratedLine16Widget.dart';
import 'package:flutterapp/haiapp/generatediphone11promax19widget/generated/GeneratedYourScheduleWidget.dart';
import 'package:flutterapp/haiapp/generatediphone11promax19widget/generated/GeneratedLine14Widget.dart';
import 'package:flutterapp/haiapp/generatediphone11promax19widget/generated/GeneratedLine24Widget.dart';
import 'package:flutterapp/haiapp/generatediphone11promax19widget/generated/GeneratedRectangle23Widget.dart';
import 'package:flutterapp/haiapp/generatediphone11promax19widget/generated/GeneratedLine10Widget.dart';
import 'package:flutterapp/haiapp/generatediphone11promax19widget/generated/GeneratedLine17Widget.dart';
import 'package:flutterapp/haiapp/generatediphone11promax19widget/generated/GeneratedLine12Widget.dart';
import 'package:flutterapp/haiapp/generatediphone11promax19widget/generated/GeneratedLine5Widget.dart';
import 'package:flutterapp/haiapp/generatediphone11promax19widget/generated/GeneratedLine2Widget.dart';
import 'package:flutterapp/haiapp/generatediphone11promax19widget/generated/GeneratedLine22Widget.dart';
import 'package:flutterapp/haiapp/generatediphone11promax19widget/generated/GeneratedLine19Widget.dart';
import 'package:flutterapp/haiapp/generatediphone11promax19widget/generated/GeneratedLine25Widget.dart';
import 'package:flutterapp/haiapp/generatediphone11promax19widget/generated/GeneratedLine6Widget.dart';
import 'package:flutterapp/haiapp/generatediphone11promax19widget/generated/GeneratedLine7Widget.dart';
import 'package:flutterapp/haiapp/generatediphone11promax19widget/generated/GeneratedLine20Widget.dart';
import 'package:flutterapp/haiapp/generatediphone11promax19widget/generated/GeneratedLine21Widget.dart';
import 'package:flutterapp/haiapp/generatediphone11promax19widget/generated/GeneratedLine3Widget7.dart';
import 'package:flutterapp/haiapp/generatediphone11promax19widget/generated/GeneratedRectangle21Widget.dart';
import 'package:flutterapp/haiapp/generatediphone11promax19widget/generated/GeneratedRectangle24Widget.dart';
import 'package:flutterapp/haiapp/generatediphone11promax19widget/generated/GeneratedLine23Widget.dart';
import 'package:flutterapp/haiapp/generatediphone11promax19widget/generated/GeneratedRectangle22Widget.dart';
import 'package:flutterapp/haiapp/generatediphone11promax19widget/generated/GeneratedRectangle8Widget2.dart';
import 'package:flutterapp/haiapp/generatediphone11promax19widget/generated/GeneratedLine15Widget.dart';
import 'package:flutterapp/haiapp/generatediphone11promax19widget/generated/GeneratedLine13Widget.dart';
import 'package:flutterapp/haiapp/generatediphone11promax19widget/generated/GeneratedDoneWidget.dart';
import 'package:flutterapp/haiapp/generatediphone11promax19widget/generated/GeneratedLessonTimetableWidget.dart';
import 'package:flutterapp/haiapp/generatediphone11promax19widget/generated/GeneratedLine4Widget7.dart';
import 'package:flutterapp/haiapp/generatediphone11promax19widget/generated/GeneratedLine18Widget.dart';
import 'package:flutterapp/haiapp/generatediphone11promax19widget/generated/GeneratedLine9Widget.dart';
import 'package:flutterapp/haiapp/generatediphone11promax19widget/generated/GeneratedLine8Widget.dart';

/* Frame iPhone 11 Pro Max - 19
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProMax19Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Visibility(
      visible: false,
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Container(
          width: 414.0,
          height: 896.0,
          child: Stack(
              fit: StackFit.expand,
              alignment: Alignment.center,
              overflow: Overflow.visible,
              children: [
                ClipRRect(
                  borderRadius: BorderRadius.zero,
                  child: Container(
                    color: Color.fromARGB(255, 183, 169, 201),
                  ),
                ),
                Positioned(
                  left: 0.000244140625,
                  top: 148.0,
                  right: null,
                  bottom: null,
                  width: 414.0007629394531,
                  height: 747.7596435546875,
                  child: GeneratedRectangle8Widget2(),
                ),
                Positioned(
                  left: 41.0,
                  top: 107.0,
                  right: null,
                  bottom: null,
                  width: 322.0,
                  height: 49.0,
                  child: GeneratedLessonTimetableWidget(),
                ),
                Positioned(
                  left: 47.0,
                  top: 499.0,
                  right: null,
                  bottom: null,
                  width: 286.0,
                  height: 49.0,
                  child: GeneratedEventReminderWidget(),
                ),
                Positioned(
                  left: 38.0,
                  top: 165.0,
                  right: null,
                  bottom: null,
                  width: 329.0,
                  height: 297.0,
                  child: GeneratedRectangle21Widget(),
                ),
                Positioned(
                  left: 76.0,
                  top: 193.0,
                  right: null,
                  bottom: null,
                  width: 247.0020294189453,
                  height: 1.0,
                  child: GeneratedLine13Widget(),
                ),
                Positioned(
                  left: 76.0,
                  top: 230.0,
                  right: null,
                  bottom: null,
                  width: 247.0020294189453,
                  height: 1.0,
                  child: GeneratedLine12Widget(),
                ),
                Positioned(
                  left: 76.0,
                  top: 310.0,
                  right: null,
                  bottom: null,
                  width: 247.0020294189453,
                  height: 1.0,
                  child: GeneratedLine10Widget(),
                ),
                Positioned(
                  left: 76.0,
                  top: 416.0,
                  right: null,
                  bottom: null,
                  width: 247.0020294189453,
                  height: 1.0,
                  child: GeneratedLine8Widget(),
                ),
                Positioned(
                  left: 98.0,
                  top: 165.0,
                  right: null,
                  bottom: null,
                  width: 295.0,
                  height: 1.0,
                  child: GeneratedLine6Widget(),
                ),
                Positioned(
                  left: 146.0,
                  top: 165.0,
                  right: null,
                  bottom: null,
                  width: 295.0,
                  height: 1.0,
                  child: GeneratedLine5Widget(),
                ),
                Positioned(
                  left: 247.0,
                  top: 164.0,
                  right: null,
                  bottom: null,
                  width: 295.0,
                  height: 1.0,
                  child: GeneratedLine2Widget(),
                ),
                Positioned(
                  left: 197.0,
                  top: 165.0,
                  right: null,
                  bottom: null,
                  width: 295.0,
                  height: 1.0,
                  child: GeneratedLine4Widget7(),
                ),
                Positioned(
                  left: 302.0,
                  top: 164.0,
                  right: null,
                  bottom: null,
                  width: 295.0,
                  height: 1.0,
                  child: GeneratedLine3Widget7(),
                ),
                Positioned(
                  left: 76.0,
                  top: 381.0,
                  right: null,
                  bottom: null,
                  width: 247.0020294189453,
                  height: 1.0,
                  child: GeneratedLine7Widget(),
                ),
                Positioned(
                  left: 76.0,
                  top: 270.0,
                  right: null,
                  bottom: null,
                  width: 247.0020294189453,
                  height: 1.0,
                  child: GeneratedLine11Widget(),
                ),
                Positioned(
                  left: 76.0,
                  top: 346.0,
                  right: null,
                  bottom: null,
                  width: 247.0020294189453,
                  height: 1.0,
                  child: GeneratedLine9Widget(),
                ),
                Positioned(
                  left: 39.0,
                  top: 567.0,
                  right: null,
                  bottom: null,
                  width: 329.0,
                  height: 297.0,
                  child: GeneratedRectangle22Widget(),
                ),
                Positioned(
                  left: 77.0,
                  top: 595.0,
                  right: null,
                  bottom: null,
                  width: 247.0020294189453,
                  height: 1.0,
                  child: GeneratedLine14Widget(),
                ),
                Positioned(
                  left: 77.0,
                  top: 632.0,
                  right: null,
                  bottom: null,
                  width: 247.0020294189453,
                  height: 1.0,
                  child: GeneratedLine15Widget(),
                ),
                Positioned(
                  left: 77.0,
                  top: 712.0,
                  right: null,
                  bottom: null,
                  width: 247.0020294189453,
                  height: 1.0,
                  child: GeneratedLine16Widget(),
                ),
                Positioned(
                  left: 77.0,
                  top: 818.0,
                  right: null,
                  bottom: null,
                  width: 247.0020294189453,
                  height: 1.0,
                  child: GeneratedLine17Widget(),
                ),
                Positioned(
                  left: 99.0,
                  top: 567.0,
                  right: null,
                  bottom: null,
                  width: 295.0,
                  height: 1.0,
                  child: GeneratedLine18Widget(),
                ),
                Positioned(
                  left: 147.0,
                  top: 567.0,
                  right: null,
                  bottom: null,
                  width: 295.0,
                  height: 1.0,
                  child: GeneratedLine19Widget(),
                ),
                Positioned(
                  left: 248.0,
                  top: 566.0,
                  right: null,
                  bottom: null,
                  width: 295.0,
                  height: 1.0,
                  child: GeneratedLine20Widget(),
                ),
                Positioned(
                  left: 198.0,
                  top: 567.0,
                  right: null,
                  bottom: null,
                  width: 295.0,
                  height: 1.0,
                  child: GeneratedLine21Widget(),
                ),
                Positioned(
                  left: 303.0,
                  top: 566.0,
                  right: null,
                  bottom: null,
                  width: 295.0,
                  height: 1.0,
                  child: GeneratedLine22Widget(),
                ),
                Positioned(
                  left: 77.0,
                  top: 783.0,
                  right: null,
                  bottom: null,
                  width: 247.0020294189453,
                  height: 1.0,
                  child: GeneratedLine23Widget(),
                ),
                Positioned(
                  left: 77.0,
                  top: 672.0,
                  right: null,
                  bottom: null,
                  width: 247.0020294189453,
                  height: 1.0,
                  child: GeneratedLine24Widget(),
                ),
                Positioned(
                  left: 77.0,
                  top: 748.0,
                  right: null,
                  bottom: null,
                  width: 247.0020294189453,
                  height: 1.0,
                  child: GeneratedLine25Widget(),
                ),
                Positioned(
                  left: 67.0,
                  top: 39.0,
                  right: null,
                  bottom: null,
                  width: 262.0,
                  height: 49.0,
                  child: GeneratedYourScheduleWidget(),
                ),
                Positioned(
                  left: 360.0,
                  top: 861.0,
                  right: null,
                  bottom: null,
                  width: 49.0,
                  height: 26.0,
                  child: GeneratedRectangle23Widget(),
                ),
                Positioned(
                  left: 369.0,
                  top: 867.0,
                  right: null,
                  bottom: null,
                  width: 40.0,
                  height: 19.0,
                  child: GeneratedDoneWidget(),
                ),
                Positioned(
                  left: 7.0,
                  top: 855.0,
                  right: null,
                  bottom: null,
                  width: 75.0,
                  height: 33.0,
                  child: GeneratedRectangle24Widget(),
                ),
                Positioned(
                  left: 16.0,
                  top: 862.0,
                  right: null,
                  bottom: null,
                  width: 64.0,
                  height: 23.0,
                  child: GeneratedAddEditWidget(),
                )
              ]),
        ),
      ),
    ));
  }
}
