import 'package:flutter/material.dart';
import 'package:flutterapp/haiapp/generatedsettingsframewidget/generated/GeneratedPageHeaderWidget13.dart';
import 'package:flutterapp/haiapp/generatedsettingsframewidget/generated/GeneratedOptionsWidget.dart';

/* Frame Settings frame
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSettingsframeWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        decoration: BoxDecoration(
          gradient: LinearGradient(
            begin: Alignment(0.0, -1.0),
            end: Alignment(0.0, 0.9999999999999998),
            stops: [0.0, 1.0],
            colors: [
              Color.fromARGB(255, 246, 243, 246),
              Color.fromARGB(0, 255, 255, 255)
            ],
          ),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              Positioned(
                left: 33.0,
                top: 17.0,
                right: 38.0,
                bottom: null,
                width: null,
                height: 36.0,
                child: GeneratedPageHeaderWidget13(),
              ),
              Positioned(
                left: 11.0,
                top: 102.0,
                right: null,
                bottom: null,
                width: 390.0,
                height: 548.0,
                child: GeneratedOptionsWidget(),
              )
            ]),
      ),
    ));
  }
}
