import 'package:flutter/material.dart';
import 'package:flutterapp/haiapp/generatedverificationcodeframewidget/generated/GeneratedPageHeaderWidget6.dart';
import 'package:flutterapp/haiapp/generatedverificationcodeframewidget/generated/GeneratedButtonPrimaryWidget9.dart';
import 'package:flutterapp/haiapp/generatedverificationcodeframewidget/generated/GeneratedInputTextWidget9.dart';

/* Frame Verification Code frame
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVerificationCodeframeWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        decoration: BoxDecoration(
          gradient: LinearGradient(
            begin: Alignment(0.0, -1.0),
            end: Alignment(0.0, 0.9999999999999998),
            stops: [0.0, 1.0],
            colors: [
              Color.fromARGB(255, 246, 243, 246),
              Color.fromARGB(0, 255, 255, 255)
            ],
          ),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              Positioned(
                left: 36.0,
                top: 318.0,
                right: 35.0,
                bottom: null,
                width: null,
                height: 50.0,
                child: GeneratedInputTextWidget9(),
              ),
              Positioned(
                left: 20.0,
                top: 68.0,
                right: 51.0,
                bottom: null,
                width: null,
                height: 36.0,
                child: GeneratedPageHeaderWidget6(),
              ),
              Positioned(
                left: 32.0,
                top: null,
                right: 39.0,
                bottom: 397.0,
                width: null,
                height: 51.0,
                child: GeneratedButtonPrimaryWidget9(),
              )
            ]),
      ),
    ));
  }
}
