import 'package:flutter/material.dart';
import 'package:flutterapp/haiapp/generatedvideocallubframewidget/generated/GeneratedFooterWidget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/haiapp/generatedvideocallubframewidget/generated/GeneratedDeviceBGWidget.dart';
import 'package:flutterapp/haiapp/generatedvideocallubframewidget/generated/GeneratedCallbtnWidget.dart';
import 'package:flutterapp/haiapp/generatedvideocallubframewidget/generated/GeneratedCameraandfilterWidget.dart';

/* Frame Video call UB frame
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVideocallUBframeWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 918.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 414.0,
                      height: 918.0,
                      decoration: BoxDecoration(
                        gradient: LinearGradient(
                          begin: Alignment(0.0, -1.0),
                          end: Alignment(0.0, 0.9999999999999998),
                          stops: [0.0, 1.0],
                          colors: [
                            Color.fromARGB(255, 246, 243, 246),
                            Color.fromARGB(0, 255, 255, 255)
                          ],
                        ),
                      ),
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                double percentWidth = 1.0;
                                double scaleX =
                                    (constraints.maxWidth * percentWidth) /
                                        414.0;

                                double percentHeight = 1.0011160524322575;
                                double scaleY =
                                    (constraints.maxHeight * percentHeight) /
                                        919.0245361328125;

                                return Stack(children: [
                                  TransformHelper.translateAndScale(
                                      translateX: 0,
                                      translateY: constraints.maxHeight *
                                          -0.027901786604737924,
                                      translateZ: 0,
                                      scaleX: scaleX,
                                      scaleY: scaleY,
                                      scaleZ: 1,
                                      child: GeneratedDeviceBGWidget())
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.8182367149758454;

                                final double height =
                                    constraints.maxHeight * 0.0580357902709695;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.09178743961352658,
                                      y: constraints.maxHeight *
                                          0.7962962962962963,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratedFooterWidget(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width = constraints.maxWidth * 0.5;

                                final double height =
                                    constraints.maxHeight * 0.09486605243225762;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.24154589371980675,
                                      y: constraints.maxHeight *
                                          0.6878422755821079,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratedCameraandfilterWidget(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.19073475271031476;

                                final double height =
                                    constraints.maxHeight * 0.08559475900820397;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.488980648022343,
                                      y: constraints.maxHeight *
                                          0.8528891835597086,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratedCallbtnWidget(),
                                      ))
                                ]);
                              }),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
