import 'package:flutter/material.dart';
import 'package:flutterapp/haiapp/generatedsignupframewidget/generated/GeneratedPageHeaderWidget3.dart';
import 'package:flutterapp/haiapp/generatedsignupframewidget/generated/GeneratedButtonPrimaryWidget6.dart';
import 'package:flutterapp/haiapp/generatedsignupframewidget/generated/GeneratedForgotyourpasswordWidget1.dart';
import 'package:flutterapp/haiapp/generatedsignupframewidget/generated/GeneratedHaveanaccountWidget.dart';
import 'package:flutterapp/haiapp/generatedsignupframewidget/generated/GeneratedInputTextWidget2.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/haiapp/generatedsignupframewidget/generated/GeneratedCheckboxOptionEmptyWidget.dart';
import 'package:flutterapp/haiapp/generatedsignupframewidget/generated/GeneratedInputTextWidget4.dart';
import 'package:flutterapp/haiapp/generatedsignupframewidget/generated/GeneratedInputTextWidget3.dart';

/* Frame Sign Up frame
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSignUpframeWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        decoration: BoxDecoration(
          gradient: LinearGradient(
            begin: Alignment(0.0, -1.0),
            end: Alignment(0.0, 0.9999999999999998),
            stops: [0.0, 1.0],
            colors: [
              Color.fromARGB(255, 246, 243, 246),
              Color.fromARGB(0, 255, 255, 255)
            ],
          ),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              Positioned(
                left: 36.0,
                top: 318.0,
                right: 35.0,
                bottom: null,
                width: null,
                height: 50.0,
                child: GeneratedInputTextWidget2(),
              ),
              Positioned(
                left: 36.0,
                top: 414.0,
                right: 35.0,
                bottom: null,
                width: null,
                height: 50.0,
                child: GeneratedInputTextWidget3(),
              ),
              Positioned(
                left: null,
                top: null,
                right: null,
                bottom: 198.0,
                width: 180.0,
                height: 21.0,
                child: TransformHelper.translate(
                    x: -20.00,
                    y: 0.00,
                    z: 0,
                    child: GeneratedForgotyourpasswordWidget1()),
              ),
              Positioned(
                left: null,
                top: null,
                right: null,
                bottom: 150.0,
                width: 140.0,
                height: 21.0,
                child: TransformHelper.translate(
                    x: -29.00,
                    y: 0.00,
                    z: 0,
                    child: GeneratedHaveanaccountWidget()),
              ),
              Positioned(
                left: 20.0,
                top: 104.0,
                right: 51.0,
                bottom: null,
                width: null,
                height: 36.0,
                child: GeneratedPageHeaderWidget3(),
              ),
              Positioned(
                left: 42.0,
                top: 222.0,
                right: 29.0,
                bottom: null,
                width: null,
                height: 50.0,
                child: GeneratedInputTextWidget4(),
              ),
              Positioned(
                left: 48.0,
                top: 518.0,
                right: 23.0,
                bottom: null,
                width: null,
                height: 17.0,
                child: GeneratedCheckboxOptionEmptyWidget(),
              ),
              Positioned(
                left: 36.0,
                top: null,
                right: 35.0,
                bottom: 248.0,
                width: null,
                height: 51.0,
                child: GeneratedButtonPrimaryWidget6(),
              )
            ]),
      ),
    ));
  }
}
