import 'package:flutter/material.dart';
import 'package:flutterapp/haiapp/generatedfeelingsickframewidget/generated/GeneratedContentMarketBlockWidget1.dart';
import 'package:flutterapp/haiapp/generatedfeelingsickframewidget/generated/GeneratedHomeWidget3.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/haiapp/generatedfeelingsickframewidget/generated/GeneratedContentMarketBlockWidget.dart';
import 'package:flutterapp/haiapp/generatedfeelingsickframewidget/generated/GeneratedHavingcovid19symptomsoffeelingunwellcalltheclinicnoweit.dart';

/* Frame Feeling Sick frame
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedFeelingSickframeWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        decoration: BoxDecoration(
          gradient: LinearGradient(
            begin: Alignment(0.0, -1.0),
            end: Alignment(0.0, 0.9999999999999998),
            stops: [0.0, 1.0],
            colors: [
              Color.fromARGB(255, 246, 243, 246),
              Color.fromARGB(0, 255, 255, 255)
            ],
          ),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              Positioned(
                left: 42.0,
                top: 472.0,
                right: null,
                bottom: null,
                width: 110.0,
                height: 177.0,
                child: GeneratedContentMarketBlockWidget(),
              ),
              Positioned(
                left: 252.0,
                top: 472.0,
                right: null,
                bottom: null,
                width: 110.0,
                height: 177.0,
                child: GeneratedContentMarketBlockWidget1(),
              ),
              Positioned(
                left: 71.0,
                top: 275.0,
                right: null,
                bottom: null,
                width: 293.0,
                height: 36.0,
                child:
                    GeneratedHavingcovid19symptomsoffeelingunwellcalltheclinicnoweit(),
              ),
              Positioned(
                left: 152.0,
                top: null,
                right: null,
                bottom: null,
                width: 120.0,
                height: 51.0,
                child: TransformHelper.translate(
                    x: 0.00, y: 324.50, z: 0, child: GeneratedHomeWidget3()),
              )
            ]),
      ),
    ));
  }
}
